### ISSUE TITLE
Use zend_hash_str_find() as replacement for zend_hash_find()

### ISSUE THREAD

**Issue by amishmm** [the-kbA-team/php-pam#2]
zend_hash_str_find() could easily be replaced by zend_hash_str_find() instead of multi-line code.

See suggested code changes here:
https://github.com/the-kbA-team/php-pam/commit/156fa9f3666a3d85988d23515735839f67d24695#r30841135

Source:
https://wiki.php.net/phpng-upgrading#hashtable_api

**Comment by gregor-j** [comment]
I also tried to restore the spacing from the PECL module 1.0.3 in order make the actual changes between this version and 1.0.3 from pecl more visible.
